name: flutter_demo
description: flutter开发基础框架.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #  网络情况库
  dio: ^2.1.0
  #  轮播图库
  flutter_swiper: ^1.1.6
  #  屏幕适配
  flutter_screenutil: ^0.5.1
  #  移动平台中启动URL
  url_launcher: ^5.0.2
  #  上拉下载刷新
  flutter_easyrefresh: ^1.2.7
  # json转化库
  json_annotation: ^2.0.0
  # 状态管理库
  provide: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
flutter:
  uses-material-design: true
